import { isNotEmpty } from "@mantine/form";

const initialValues = {
	business_model_id: "",
	pos_invoice_mode_id: "",
	country_id: "",
	currency_id: "",
	address: "",
	sku_warehouse: false,
	sku_category: false,
	vat_enable: false,
	sd_enable: false,
	hs_code_enable: false,
	zakat_enable: false,
	zakat_percent: 0,
	sd_percent: 0,
	ait_percent: 0,
	ait_enable: false,
	production_type: "",
	invoice_comment: "",
	logo: "",
	remove_image: false,
	invoice_print_logo: false,
	print_outstanding: false,
	pos_print: false,
	is_print_header: false,
	is_invoice_title: false,
	is_print_footer: false,
	is_powered: false,
	print_footer_text: "",
	body_font_size: 0,
	invoice_height: 0,
	invoice_width: 0,
	border_color: "",
	border_width: 0,
	print_left_margin: 0,
	print_top_margin: 0,
	custom_invoice: false,
	bonus_from_stock: false,
	is_unit_price: false,
	zero_stock: false,
	stock_item: false,
	custom_invoice_print: false,
	is_stock_history: false,
	condition_sales: false,
	store_ledger: false,
	is_marketing_executive: false,
	tlo_commission: false,
	sales_return: false,
	sr_commission: false,
	due_sales_without_customer: false,
	is_description: false,
	is_zero_receive_allow: false,
	is_purchase_by_purchase_price: false,
	is_pos: false,
	is_pay_first: false,
	is_sales_auto_approved: false,
	is_purchase_auto_approved: false,
	is_active_sms: false,
	is_kitchen: false,
};

export const getConfigurationFormInitialValues = () => {
	return {
		initialValues,

		validate: {
			business_model_id: isNotEmpty(),
			country_id: isNotEmpty(),
			currency_id: isNotEmpty(),
		},
	};
};
